=== hoelzl/claas/src/claas/azav-kurs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://xsd.coding-academy.com/claas/azav-kurs"
           xmlns="http://xsd.coding-academy.com/claas/azav-kurs"
           elementFormDefault="qualified">

  <xs:element name="kurs">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titel" type="xs:string"/>
        <xs:element name="modul" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titel" type="xs:string"/>
              <xs:element name="beschreibung" type="xs:string" minOccurs="0"/>
              <xs:choice maxOccurs="unbounded">
                <xs:element name="themengruppe">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="zusammenfassung" type="xs:string"/>
                      <xs:element name="detailthemen" minOccurs="0">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="thema" maxOccurs="unbounded">
                              <xs:complexType>
                                <xs:sequence>
                                  <xs:element name="inhalt" type="xs:string"/>
                                  <xs:element name="dauer" type="xs:integer"
                                              minOccurs="0" default="1"/>
                                  <xs:element name="methodik" type="xs:string"
                                              minOccurs="0"
                                              default="Frontalunterricht"/>
                                  <xs:element name="material" type="xs:string"
                                              minOccurs="0"
                                              default="Folien, Notebooks"/>
                                </xs:sequence>
                              </xs:complexType>
                            </xs:element>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
                <xs:element name="abschnitt" type="xs:string"/>
                <xs:element name="woche" type="xs:string"/>
              </xs:choice>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== hoelzl/claas/tests/full_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<kurs xmlns="http://xsd.coding-academy.com/claas/azav-kurs"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://xsd.coding-academy.com/claas/azav-kurs https://raw.githubusercontent.com/hoelzl/claas/master/src/claas/azav-kurs.xsd">
  <titel>Kurs Titel</titel>
  <modul>
    <titel>Modul 1 Titel</titel>
    <beschreibung>Modul 1 Beschreibung</beschreibung>
    <thema>
      <inhalt>Thema 1 Inhalt</inhalt>
      <dauer>3</dauer>
    </thema>
    <bemerkung>Bemerkung 1</bemerkung>
    <bemerkung>Bemerkung 2</bemerkung>
    <thema>
      <inhalt>Thema 2 Inhalt</inhalt>
      <dauer>5</dauer>
      <methodik>Gruppenarbeit</methodik>
      <material>Handouts</material>
    </thema>
  </modul>
</kurs>
